create table if not exists public.recovery_codes (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  method text not null check (method in ('email', 'sms', 'whatsapp')),
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0 check (attempts >= 0),
  used_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists recovery_codes_lookup_idx
  on public.recovery_codes (identifier_hash, method, created_at desc);

create index if not exists recovery_codes_expiry_idx
  on public.recovery_codes (expires_at);

alter table public.recovery_codes enable row level security;

-- No client-facing policy: recovery codes are server-side secrets and must
-- only be accessed by trusted server code using a privileged connection.
